### ISSUE TITLE
`pnpm run dev` fails because `GITHUB_PERSONAL_ACCESS_TOKEN` is missing

### ISSUE THREAD

**Issue by penberg** [Fredkiss3/gh-next#2]
I followed the installation instructions, but `pnpm run dev` fails because `GITHUB_PERSONAL_ACCESS_TOKEN` is not mentioned in `.env.example`, but seems to be required:

```
penberg@vonneumann www % pnpm run dev

> gh-issues-next@0.1.0 dev /Users/penberg/src/penberg/gh-next/www
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /Users/penberg/src/penberg/gh-next/www/.env.local
❌ Invalid environment variables: { GITHUB_PERSONAL_ACCESS_TOKEN: [ 'Required' ] }
- error Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Invalid environment variables
    at d (file:///Users/penberg/src/penberg/gh-next/www/node_modules/.pnpm/@t3-oss+env-nextjs@0.4.1_typescript@5.1.3_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:424)
    at a (file:///Users/penberg/src/penberg/gh-next/www/node_modules/.pnpm/@t3-oss+env-nextjs@0.4.1_typescript@5.1.3_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:614)
    at P (file:///Users/penberg/src/penberg/gh-next/www/node_modules/.pnpm/@t3-oss+env-nextjs@0.4.1_typescript@5.1.3_zod@3.21.4/node_modules/@t3-oss/env-nextjs/dist/index.mjs:1:887)
    at file:///Users/penberg/src/penberg/gh-next/www/src/env.mjs:5:20
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfig (/Users/penberg/src/penberg/gh-next/www/node_modules/.pnpm/next@13.4.12_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/config.js:546:36)
    at async NextServer.prepare (/Users/penberg/src/penberg/gh-next/www/node_modules/.pnpm/next@13.4.12_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next.js:161:24) {
  type: 'Error'
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Fredkiss3** [comment]
Hello @penberg thank you for opening this issue. 

I just forgot to add it to the `env.example` , I will add it when I get the time to work on it. 

But this env corresponds to the GitHub App Token, mentioned in the requirements, it is used to authenticate users with GitHub OAuth. 

> A registered github app for authenticating users
